language: java

jobs:
  allow_failures:
    - stage: e2e
    - name: "E2E tests"
  include:
    - stage: test
      name: "Java 11 - unit & integration tests code coverage + snapshot upload"
      language: java
      jdk: openjdk11
      script:
        - mvn -Pjava11 clean verify jacoco:report
        - mvn -Pjava11 coveralls:report
        - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_TAG" = "" ]; then mvn -Pjava11 deploy -DskipTests --settings deploy-settings.xml; fi

    - stage: test
      name: "Java 8 - unit & integration tests"
      language: java
      jdk: openjdk8
      script:
        - mvn -Pjava8 clean verify

    - stage: test
      name: "Java 11 - unit & framework integration tests"
      language: java
      jdk: openjdk11
      script:
        - mvn -Pframework-integration-tests,java11 -pl '!fluentlenium-integration-tests,!fluentlenium-cucumber,!fluentlenium-spock,!fluentlenium-coverage-report' clean test

    - stage: test
      name: "Java 11 - compile examples"
      language: java
      jdk: openjdk11
      script:
        - mvn -Pexamples,java11 clean compile

    - stage: test
      name: "Java 11 - javadoc"
      language: java
      jdk: openjdk11
      script:
        - mvn -Pjava11 javadoc:aggregate

    - stage: test
      name: "Ruby - Docs build"
      language: ruby
      rvm:
        - 2.6
      before_script:
        - chmod +x ./docs/cibuild
      script:
        - ( cd docs && ./cibuild )
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      sudo: false

    - stage: e2e
      name: "Edge"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=edge -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      allow_failures:
      if: type = pull_request

    - stage: e2e
      name: "IE"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=ie -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

    - stage: e2e
      name: "Chrome"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=chrome -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

    - stage: e2e
      name: "Firefox"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=firefox -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

    - stage: e2e
      name: "Safari"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=safari -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

    - stage: e2e
      name: "Iphone Web test (Safari on Iphone)"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=iphone -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

    - stage: e2e
      name: "Android Web test (Chrome on Android device)"
      language: java
      jdk: openjdk11
      script:
        - cd examples/spring && mvn clean test -DbrowserName=android -Dmobile.simulator=false -DuseHub=true -DgridUrl=$BROWSERSTACK_GRID_URL
      if: type = pull_request

env:
  global:
    # env.CI_DEPLOY_USERNAME
    - secure: XhWeOh6PhDFEH/DTPhAbH04rysTdKWUoQxfYI7YjlrRznX0YKBRLVHIXn68TdzC/ucX0t+XzO2vOVoR53lSBYr45P5ZnO5+rFjVLhfhUDQWv3BibtaH6oCYM0lwvtA6mWKA6thWfvqOAvYgTUhdgEwaoVK/oHidW0KHNxNC0Ty8=
    # env.CI_DEPLOY_PASSWORD
    - secure: Pw6Aik2ws5z/VVKZ7J7+BtTJ79IMYwYde/C9LocyQtEeGxET7il57WZ2T2TyIxu9/tFtzX8N6fpf5j1Q64dUrL8Ki6R7phNvcFRl537AXINBSVuGz6rA/h8Vqx31wsHoTnl8tY6J6fUIHBF2KxvY38NzXl2g5v1n0eCmhyYxor8=
