jobs:
  include:
    - stage: test
      name: "Java 11 - unit & integration tests code coverage + snapshot upload"
      language: java
      jdk: oraclejdk11
      script:
        - mvn clean verify jacoco:report
        - mvn coveralls:report
        - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_TAG" = "" ]; then mvn deploy -DskipTests --settings deploy-settings.xml; fi

    - stage: test
      name: "Java 11 - unit & framework integration tests"
      language: java
      jdk: oraclejdk11
      script:
        - mvn -Pframework-integration-tests clean test

    - stage: test
      name: "Java 11 - compile examples"
      language: java
      jdk: oraclejdk11
      script:
        - mvn -Pexamples clean compile

    - stage: test
      name: "Java 8 - unit & integration tests"
      language: java
      jdk: oraclejdk8
      script:
        - mvn clean verify -Drevision=3.8.0-SNAPSHOT

    - stage: test
      name: "Ruby - Docs build"
      language: ruby
      rvm:
        - 2.6
      before_script:
        - chmod +x ./docs/cibuild
      script:
        - ( cd docs && ./cibuild )
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      sudo: false

env:
  global:
    # env.CI_DEPLOY_USERNAME
    - secure: XhWeOh6PhDFEH/DTPhAbH04rysTdKWUoQxfYI7YjlrRznX0YKBRLVHIXn68TdzC/ucX0t+XzO2vOVoR53lSBYr45P5ZnO5+rFjVLhfhUDQWv3BibtaH6oCYM0lwvtA6mWKA6thWfvqOAvYgTUhdgEwaoVK/oHidW0KHNxNC0Ty8=
    # env.CI_DEPLOY_PASSWORD
    - secure: Pw6Aik2ws5z/VVKZ7J7+BtTJ79IMYwYde/C9LocyQtEeGxET7il57WZ2T2TyIxu9/tFtzX8N6fpf5j1Q64dUrL8Ki6R7phNvcFRl537AXINBSVuGz6rA/h8Vqx31wsHoTnl8tY6J6fUIHBF2KxvY38NzXl2g5v1n0eCmhyYxor8=
